"""Add course_end_date field

Revision ID: 031e320f399c
Revises: c755afcd69d6
Create Date: 2026-02-10 08:14:00.530477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031e320f399c'
down_revision = 'c755afcd69d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrolments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_end_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrolments', schema=None) as batch_op:
        batch_op.drop_column('course_end_date')

    # ### end Alembic commands ###
