"""Enrolment schema created

Revision ID: c755afcd69d6
Revises: 
Create Date: 2026-02-05 09:04:25.577072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c755afcd69d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrolments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('invoice_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELED', 'COMPLETED', name='status'), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'FAILED', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_enrolments')
    )
    with op.batch_alter_table('enrolments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrolments_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrolments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrolments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrolments_user_id'))
        batch_op.drop_index(batch_op.f('ix_enrolments_course_id'))

    op.drop_table('enrolments')
    # ### end Alembic commands ###
