from pydantic import BaseModel

class LoginSchema(BaseModel):
    """
    Schema for user login.

    Attributes:
        identifier (str): Username or email of the user.
        password (str): User's password.
    """
    identifier: str
    password: str

class TokenPairSchema(BaseModel):
    """
    Schema representing JWT token pair.

    Attributes:
        access_token (str): JWT access token.
        refresh_token (str): JWT refresh token.
    """
    access_token: str
    refresh_token: str

class VerifyMfaSchema(BaseModel):
    """
    Schema for verifying MFA code.

    Attributes:
        user_id (str): ID of the user performing MFA.
        code (str): One-time MFA code generated by authenticator app.
    """
    user_id: str
    code: str

class AccessTokenSchema(BaseModel):
    """
    Schema for returning only the access token.

    Attributes:
        access_token (str): JWT access token.
    """
    access_token: str